# -*- coding: utf-8 -*-
"""AgenteExtensaoIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_sbhNUFdLMSCuLtNSYDORs8mN00o4jt
"""

!pip install --upgrade langchain pdfplumber

!pip install langchain-text-splitters

import os

# Listar todos os arquivos na pasta /content/
files_in_content = os.listdir('/content/')

# Filtrar por arquivos .pdf e .docx
pdf_files = [f for f in files_in_content if f.endswith('.pdf')]
docx_files = [f for f in files_in_content if f.endswith('.docx')]

print(f"Arquivos PDF encontrados: {pdf_files}")
print(f"Arquivos DOCX encontrados: {docx_files}")

if not pdf_files:
    print("\nNão foram encontrados arquivos PDF na pasta /content/. Por favor, certifique-se de que os PDFs estejam lá ou confirme se você gostaria de processar os arquivos DOCX, o que exigirá uma biblioteca diferente.")
else:
    print("\nArquivos PDF encontrados. Podemos prosseguir com o carregamento e configuração do RAG.")

!pip install python-docx

from docx import Document

def extract_text_from_docx(docx_path):
    try:
        document = Document(docx_path)
        full_text = []
        for para in document.paragraphs:
            full_text.append(para.text)
        return '\n'.join(full_text)
    except Exception as e:
        print(f"Erro ao ler o arquivo {docx_path}: {e}")
        return None

# Assuming docx_files is already defined from a previous cell
# If not, you'd need to re-run the cell that identifies docx_files

if 'docx_files' not in locals():
    print("A variável 'docx_files' não foi encontrada. Por favor, execute a célula anterior que lista os arquivos DOCX.")
else:
    documents_content = {}
    for docx_file in docx_files:
        file_path = os.path.join('/content/', docx_file)
        content = extract_text_from_docx(file_path)
        if content:
            documents_content[docx_file] = content
            print(f"Conteúdo extraído de '{docx_file}' (primeiros 200 caracteres):\n{content[:200]}...\n")

    if documents_content:
        print(f"Total de {len(documents_content)} documentos DOCX processados com sucesso.")
    else:
        print("Nenhum conteúdo foi extraído dos documentos DOCX.")

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document # Changed import path for Document

# Combine all extracted content into a single list of LangChain Document objects
# Each document will correspond to one original DOCX file, with its full content.
langchain_documents = []
for docx_file, content in documents_content.items():
    # Optionally, you can add metadata to each document, e.g., the source filename
    langchain_documents.append(Document(page_content=content, metadata={'source': docx_file}))

# Initialize the text splitter
# You can adjust chunk_size and chunk_overlap based on your needs and the nature of your documents
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,  # Max size of each chunk
    chunk_overlap=200,  # Overlap between chunks to maintain context
    length_function=len,
    add_start_index=True,
)

# Split the documents into chunks
texts = text_splitter.split_documents(langchain_documents)

print(f"Total de documentos originais: {len(langchain_documents)}")
print(f"Total de chunks gerados: {len(texts)}")

# Display a sample chunk to verify
if texts:
    print("\nPrimeiro chunk de texto:\n")
    print(texts[0].page_content[:500]) # Display first 500 characters of the first chunk
    print(f"\nMetadata do primeiro chunk: {texts[0].metadata}")
else:
    print("Nenhum chunk de texto foi gerado.")

"""# Task
Configure the agent's 'brain' by defining its Objective, Boundaries, Output Format, and Fallback mechanism to ensure it can effectively assist with extension activity submissions. This configuration will be a crucial step in setting up the Retrieval-Augmented Generation (RAG) system.

## Formulate Initial Response (Collaboration)

### Subtask:
The 'Attendant' and 'Manual Analyst' agents will collaborate to synthesize the extracted information into a coherent initial response. The 'Manual Analyst' provides the factual content, and the 'Attendant' helps structure it in a student-friendly manner.

```markdown
### Formulando a Resposta Inicial (Colaboração entre Agentes)

#### 1. O Mecanismo de Colaboração: Transferência de Conhecimento
Após o 'Agente Analista Manual' ter extraído meticulosamente as regras, procedimentos e requisitos específicos dos *chunks* de documentos (a fase 'Reason' do ReAct), estas informações factuais são consolidadas e passadas para o 'Agente Atendente'. Esta transferência de conhecimento pode ser imaginada como uma API interna ou uma estrutura de dados bem definida que contém:

*   **Regras e Políticas**: Diretrizes explícitas sobre o envio da atividade.
*   **Passos Procedimentais**: Uma lista ordenada de ações que o aluno deve seguir.
*   **Requisitos Específicos**: Detalhes como formatos, prazos, documentos adicionais necessários.
*   **Possíveis Alertas**: Informações importantes ou comuns erros a serem evitados.

O 'Manual Analyst' atua como o especialista em conteúdo, garantindo que o que é fornecido seja preciso e diretamente verificável na base de conhecimento.

#### 2. O Papel do Agente Atendente na Estruturação da Resposta
O 'Agente Atendente', agora munido da informação bruta e factual do 'Manual Analyst', assume a responsabilidade de transformá-la em uma resposta compreensível e útil para o aluno. Considerando seu objetivo principal de "Fornecer um passo a passo detalhado para o envio da atividade de extensão", o 'Attendant' foca em:

*   **Tradução para Linguagem Clara**: Simplificar jargões técnicos ou burocráticos dos documentos em uma linguagem acessível ao aluno.
*   **Organização Lógica**: Estruturar as informações de forma sequencial e intuitiva, idealmente como um passo a passo, utilizando tópicos ou listas numeradas.
*   **Contextualização**: Conectar a informação extraída à pergunta original do aluno, garantindo que a resposta seja diretamente relevante à sua dúvida.
*   **Empatia e Aconselhamento**: Embora focado em fatos, o 'Attendant' pode adicionar um toque de assistência, guiando o aluno de forma encorajadora através do processo.

Por exemplo, se o 'Manual Analyst' extraiu: "A atividade deve ser submetida na plataforma Studeo, seção 'Minhas Atividades', em formato PDF, até as 23:59 do dia X", o 'Attendant' pode estruturar como: "Para enviar sua atividade de extensão, siga estes passos:
1.  Acesse a plataforma Studeo.
2.  Navegue até a seção 'Minhas Atividades'.
3.  Faça o upload do seu arquivo no formato PDF.
4.  O prazo final para envio é às 23:59 do dia X."

#### 3. Garantindo Coerência e Alinhamento com a Consulta Original
O 'Agente Atendente' tem a tarefa final de revisar a resposta formulada para garantir que ela seja coesa e responda diretamente à consulta inicial do estudante. Isso envolve:

*   **Revisão Cruzada**: Comparar a resposta gerada com a intenção original da pergunta do aluno para certificar-se de que nada foi esquecido ou mal interpretado.
*   **Fluidez da Narrativa**: Assegurar que as transições entre as diferentes partes da informação sejam suaves, criando uma experiência de leitura contínua.
*   **Preparação para Próximos Passos**: A resposta inicial é formulada de maneira a facilitar a aplicação dos 'Limites' e do 'Formato de Saída' na próxima etapa, garantindo que o agente esteja pronto para entregar uma mensagem final polida e conforme as diretrizes estabelecidas.

## Apply Agent Boundaries and Output Format (Attendant Agent)

### Subtask:
The 'Attendant' agent will review the formulated response to ensure it strictly adheres to the established 'Boundaries' (e.g., 'Não faça o trabalho pelo aluno') and the specified 'Output Format' (e.g., presenting information in bullet points, suggesting templates if appropriate). This is a critical 'Reason' and 'Observe' step to maintain agent integrity and usability.

```markdown
### Aplicando os Limites e o Formato de Saída do Agente (Agente Atendente)

Esta etapa é crucial para garantir que a resposta final do agente não seja apenas correta em termos de conteúdo, mas também ética, responsável e facilmente compreensível para o aluno. O 'Agente Atendente' age como um guardião da qualidade e conformidade da comunicação.

#### 1. Revisão da Resposta Inicial e Conformidade com os 'Limites' (Boundaries/Guardrails)

O 'Agente Atendente' examina a resposta inicial (formulada em colaboração com o 'Agente Analista Manual') para assegurar que ela esteja em total aderência aos 'Limites' estabelecidos. Este é um processo de autoavaliação e ajuste. Exemplos de verificações:

*   **Limite: "Não faça o trabalho pelo aluno"**:
    *   O agente procurará por trechos na resposta que possam ser interpretados como o agente realizando a tarefa em nome do aluno (e.g., "Sua introdução deve ser: [texto completo]").
    *   Se tal conteúdo for encontrado, o agente reformulará para uma orientação ("Sua introdução deve conter X e Y elementos, e um bom ponto de partida seria...") ou para exemplos de estrutura, incentivando o aluno a criar seu próprio conteúdo.

*   **Limite: "Não invente regras que não estejam no manual"**:
    *   O agente verificará se todas as informações factuais (prazos, requisitos, plataformas) presentes na resposta têm uma fonte explícita ou implícita nos *chunks* de documentos recuperados. Isso é especialmente importante para prevenir "alucinações".
    *   Caso alguma informação pareça não ter base documental ou seja inferida, o agente a removerá ou a substituirá por uma declaração de que a informação não foi encontrada nos documentos disponíveis. Isso pode, inclusive, desencadear um **Mecanismo de Fallback** se a informação for crítica e não puder ser obtida.

#### 2. Aplicação do 'Formato de Saída' Especificado

Após a verificação dos limites, o 'Agente Atendente' molda a resposta no 'Formato de Saída' pré-definido. Isso assegura consistência e clareza para o usuário. Para o nosso exemplo: "Entregar a resposta em tópicos e sugerir um template de lista de presença".

*   **Transformação em Tópicos**: Se a resposta inicial for um texto corrido ou estiver em outro formato, o agente a reestruturará em pontos-chave, utilizando marcadores ou numeração. Isso facilita a leitura e a absorção da informação.
    *   **Exemplo**: A informação extraída "A atividade deve ser enviada via portal do aluno, em formato PDF, até a data limite" seria transformada em:
        *   "Envie a atividade pelo portal do aluno."
        *   "O formato de arquivo aceito é PDF."
        *   "Observe a data limite para submissão."

*   **Sugestão de Template**: O agente detectará a necessidade de sugerir um template de lista de presença e o incorporará à resposta de forma clara e acessível, como um exemplo formatado em Markdown ou texto simples, incluindo campos como 'Nome', 'Matrícula' e 'Assinatura', conforme especificado.

#### 3. Esta Etapa como 'Reason' e 'Observe' no ReAct

Esta fase opera em um ciclo contínuo de 'Observe' e 'Reason':

*   **Observe**: O agente está constantemente "observando" a resposta gerada e comparando-a com as diretrizes internas (limites e formato). Ele "observa" se há desvios ou oportunidades de melhoria.
*   **Reason**: Com base nessas observações, o agente "raciocina" sobre como ajustar a resposta para que ela esteja em conformidade. Ele aplica regras lógicas (os limites e o formato de saída) para refinar o conteúdo e a apresentação. Se um limite for violado, o raciocínio leva à reformulação; se o formato não estiver correto, o raciocínio leva à reestruturação.

Este processo iterativo garante que a saída final seja otimizada para a intenção do usuário e para as restrições operacionais do agente, mantendo a integridade e a utilidade.

#### 4. Consequências de Não Atender aos Limites ou Formato

Se, após as tentativas de ajuste, a resposta ainda não atender aos limites ou ao formato especificado (por exemplo, informações críticas para o formato não foram extraídas ou um limite fundamental continua a ser violado), o 'Agente Atendente' poderá:

*   **Disparar um Refinamento Interno**: Solicitar ao 'Agente Analista Manual' ou a si mesmo um refinamento na extração ou na síntese da informação, com instruções mais precisas sobre o que deve ser evitado ou como deve ser formatado.
*   **Ativar o Fallback**: Se o problema for persistente ou se a conformidade for impossível sem mais informações do usuário ou uma intervenção maior, o 'Agente Atendente' ativará o Mecanismo de Fallback. Isso pode envolver pedir ao aluno para refinar sua pergunta, informar sobre a limitação de não poder gerar o conteúdo solicitado (no caso de "Não faça o trabalho pelo aluno"), ou até mesmo indicar que o sistema não pode fornecer uma resposta completamente satisfatória no momento devido a uma falha na aderência aos guardrails.

## Handle Fallback Scenarios (Attendant Agent)

### Subtask:
The 'Attendant' agent will activate the 'Fallback Mechanism' if essential information is missing, the query is ambiguous, or if the 'Manual Analyst' cannot retrieve information. This involves asking clarifying questions, informing about system limitations, or politely redirecting out-of-scope queries. This is an 'Observe' and 'Act' (re-prompt/inform) cycle.

```markdown
### Lidando com Cenários de Fallback (Agente Atendente)

#### 1. O Agente Atendente como Detector e Gerenciador de Fallback
O 'Agente Atendente' opera como a linha de frente na interação com o aluno e, crucialmente, é o componente responsável por detectar e gerenciar os cenários de fallback. Sua função é monitorar o fluxo da conversa e o estado interno do sistema para identificar desvios do caminho ideal. Esta é uma parte vital do ciclo **'Observe'** do ReAct, onde o agente está constantemente avaliando se as condições necessárias para uma resposta precisa e completa estão presentes.

#### 2. Diferenciando os Gatilhos de Fallback
O agente deve ser capaz de distinguir entre os diferentes tipos de situações que exigem um fallback, cada uma com sua resposta ideal:

*   **Informações Essenciais Ausentes**: Isso é detectado quando o 'Agente Atendente' inicia a interação (fase de 'Observação' inicial) ou durante o processamento subsequente. Por exemplo, se a consulta do aluno requer o "curso" para contextualizar a resposta, mas essa informação não foi fornecida na entrada inicial. O agente tem diretrizes explícitas sobre quais informações são mandatórias para prosseguir.

*   **Consulta Ambígua**: Se a formulação da pergunta do aluno é vaga ou pode ter múltiplas interpretações, o 'Agente Atendente' identifica essa ambiguidade. Isso pode ser feito através de análise semântica básica ou pela ausência de termos-chave específicos esperados para uma consulta bem definida.

*   **Falhas de Recuperação do 'Manual Analyst'**: O 'Agente Atendente' recebe feedback do 'Agente Analista Manual' sobre o sucesso ou falha na recuperação de documentos relevantes. Se o 'Manual Analyst' reportar que a recuperação foi insatisfatória ou que os recursos necessários estão indisponíveis (por exemplo, indicando "serviços que ainda não foram feitos" ou "Resources: []" em seu status), o 'Attendant' reconhece isso como um gatilho de fallback.

#### 3. Ações Específicas para Cada Cenário de Fallback (Fase 'Act')
Uma vez que um gatilho de fallback é identificado, o 'Agente Atendente' executa uma **'Act'** específica, conforme as regras predefinidas no 'cérebro' do agente:

*   **Para Informações Essenciais Ausentes (e.g., curso)**:
    *   **Ação**: O agente fará uma pergunta de esclarecimento direta e concisa. Exemplo: "Para que eu possa te ajudar com o processo de envio da atividade, por favor, me informe qual é o seu curso. (Ex: Engenharia de Software)"
    *   **Propósito**: Coletar os dados necessários para desbloquear a sequência de processamento e continuar a tarefa original.

*   **Para Consultas Ambíguas**:
    *   **Ação**: O agente solicitará mais detalhes ou oferecerá opções para refinar a consulta. Exemplo: "Sua pergunta é um pouco geral. Você está buscando informações sobre prazos, requisitos de formato ou o local de envio da atividade?"
    *   **Propósito**: Guiar o aluno para formular uma pergunta mais específica que o sistema possa processar eficazmente.

*   **Para Falhas de Recuperação (RAG Incompleto / Recursos Indisponíveis)**:
    *   **Ação**: O agente informará o aluno sobre a limitação de forma educada e transparente. Exemplo: "No momento, alguns dos serviços de recuperação de informações estão em desenvolvimento, ou os recursos específicos para sua consulta ainda não estão disponíveis. Posso tentar te ajudar com informações mais gerais sobre as atividades de extensão?"
    *   **Propósito**: Gerenciar expectativas do usuário, evitar a geração de informações incorretas ou incompletas e, se possível, oferecer assistência alternativa.

*   **Para Consultas Fora do Escopo**: (Embora não explicitamente mencionada no prompt como um gatilho separado, é uma consideração comum de fallback)
    *   **Ação**: O agente redirecionará a consulta gentilmente. Exemplo: "Minha função principal é auxiliar com as atividades de extensão. Para questões sobre [tópico fora do escopo], sugiro que você procure [outro recurso/departamento]."
    *   **Propósito**: Manter o agente focado em seu objetivo principal e evitar o desvio de recursos para tarefas não designadas.

#### 4. Robustez e Experiência do Usuário Através do Fallback
Este ciclo contínuo de 'Observe' (identificar o gatilho) e 'Act' (executar a resposta de fallback) é fundamental para construir um agente robusto e user-friendly. Ele evita que o agente:

*   **Forneça Informações Incorretas**: Ao não tentar adivinhar ou "alucinar" respostas quando dados cruciais ou documentos relevantes estão ausentes.
*   **Gere Respostas Incompletas**: Ao proativamente solicitar os dados necessários para uma resposta abrangente.
*   **Cause Frustração**: Ao guiar o usuário de forma clara sobre o porquê de uma resposta completa não poder ser fornecida imediatamente e quais são os próximos passos.

O Mecanismo de Fallback transforma potenciais pontos de falha em oportunidades para uma interação mais inteligente e orientada ao usuário, reforçando a confiabilidade do sistema RAG como um todo.
```

## Deliver Final Structured Response (Attendant Agent)

### Subtask:
Once the response is complete, accurate, and adheres to all defined parameters, the 'Attendant' agent will deliver the final, structured answer to the student. This is the final 'Act' to complete the interaction for the given query.

```markdown
### Entregando a Resposta Final Estruturada (Agente Atendente)

#### 1. A Finalização e Verificação da Resposta (O Último 'Act')
Após todas as etapas de coleta, recuperação, extração e refinamento (incluindo a aplicação dos limites e do formato de saída, e a gestão de quaisquer fallbacks), o 'Agente Atendente' chega ao ponto de entregar a resposta final ao aluno. Esta é a fase conclusiva do ciclo **'Act'** no framework ReAct para a consulta específica do aluno.

Neste ponto, o 'Agente Atendente' realiza uma verificação final para garantir que a resposta esteja:

*   **Completa**: Contém todas as informações necessárias para abordar a consulta do aluno, conforme o objetivo do agente de "Fornecer um passo a passo detalhado para o envio da atividade de extensão."
*   **Precisa**: As informações são factualmente corretas e baseadas exclusivamente nos documentos recuperados, sem "alucinações" ou regras inventadas, aderindo ao limite "Não invente regras que não estejam no manual".
*   **Conforme os Limites**: A resposta não faz o trabalho pelo aluno ("Não faça o trabalho pelo aluno") e respeita todas as outras diretrizes éticas e de escopo.
*   **Estruturada no Formato Correto**: A informação é apresentada em tópicos, e templates relevantes (como o de lista de presença) são sugeridos, conforme o "Formato de Saída" definido.

Essa última fase de 'Act' não é apenas sobre a entrega, mas sobre a *confirmação* de que todo o processo interno funcionou conforme o esperado e produziu uma saída de alta qualidade.

#### 2. Apresentação da Resposta ao Aluno
A entrega da resposta ao aluno é o culminar de todo o trabalho do agente. A apresentação segue rigorosamente o formato de saída especificado para garantir clareza e utilidade:

*   **Tópicos e Listas**: A resposta será predominantemente organizada em tópicos ou listas numeradas, facilitando a leitura e a compreensão do passo a passo. Cada item será conciso e direto ao ponto.

*   **Sugestão de Template (se aplicável)**: Se a consulta do aluno (ou o contexto da atividade) justificar, o agente incluirá o template de lista de presença. Este template será formatado de maneira clara, possivelmente em Markdown, para fácil visualização e cópia, contendo os campos essenciais como:
    ```
    --- Template de Lista de Presença ---

    **ATIVIDADE EXTENSIONISTA:** [Nome da Atividade]
    **DATA:** [dd/mm/aaaa]
    **LOCAL/PLATAFORMA:** [Local ou link]

    | Nome Completo | Matrícula | Assinatura/Confirmação |
    |---------------|-----------|------------------------|
    |               |           |                        |
    |               |           |                        |
    |               |           |                        |
    
    --- Fim do Template ---
    ```

*   **Linguagem Clara e Encorajadora**: A linguagem utilizada será acessível, evitando jargões excessivos, e manterá um tom de apoio e encorajamento ao aluno, refletindo o objetivo de auxiliar no processo.

*   **Contexto Mantido**: A resposta final fará referência à consulta original do aluno, garantindo que o aluno sinta que sua pergunta foi compreendida e atendida de forma personalizada.

Esta entrega final garante que o aluno receba não apenas a informação que pediu, mas uma solução bem organizada, fácil de seguir e que adere a todos os princípios e restrições configurados no 'cérebro' do agente, fechando o ciclo de interação de forma eficaz.

## Final Task

### Subtask:
Confirm that the ReAct-based workflow for the Attendant and Manual Analyst agents has been successfully defined, taking into account the current state of services and resources, and is ready for implementation within the RAG system.

```markdown
### Confirmação Final: Workflow ReAct e Configuração do 'Cérebro' do Agente

Confirmamos com sucesso a definição conceitual do workflow baseado em ReAct para os agentes Atendente e Analista Manual, que formarão a espinha dorsal do nosso sistema de Retrieval-Augmented Generation (RAG). A arquitetura lógica e o 'cérebro' do agente foram meticulosamente configurados, estabelecendo uma base robusta para sua operação:

1.  **Objetivo (Goal)**: Claramente definido como `Fornecer um passo a passo detalhado para o envio da atividade de extensão.`, garantindo que todas as ações do agente sejam direcionadas a esta finalidade crucial.

2.  **Limites (Boundaries/Guardrails)**: Foram estabelecidos guardrails essenciais, como `Não faça o trabalho pelo aluno` e `Não invente regras que não estejam no manual`, assegurando que o agente opere de forma ética, responsável e baseada exclusivamente em informações verificáveis dos documentos.

3.  **Formato de Saída (Output Format)**: O formato de entrega foi especificado para `Entregar a resposta em tópicos e sugerir um template de lista de presença`, promovendo clareza, consistência e utilidade prática para o aluno.

4.  **Mecanismo de Fallback (Fallback Mechanism)**: Configurado de maneira inteligente, exemplificado por `Se o aluno não informar o curso, pare e pergunte qual é o curso antes de continuar`, o mecanismo de fallback garante que o agente possa lidar com informações ausentes, ambiguidades ou falhas de recuperação de forma graciosa e proativa, mantendo a fluidez da interação.

O workflow ReAct foi concebido através dos seguintes estágios, que foram detalhadamente definidos conceitualmente:

*   **Observe (Agente Atendente)**: Inicia a interação com o aluno, coletando informações essenciais e contextualizando a query.
*   **Act (Agente Analista Manual)**: Simula a recuperação de documentos relevantes da base de conhecimento (representada pelos 90 *chunks* dos 27 documentos DOCX, armazenados na variável `texts`). Reconhece que, embora os *chunks* estejam prontos, a consulta a um banco de dados vetorial completo é, por enquanto, conceitual, e prepara para o fallback em caso de falha de recuperação.
*   **Reason (Agente Analista Manual)**: Extrai meticulosamente regras e informações dos *chunks* recuperados, aderindo estritamente aos limites de não 'inventar' regras.
*   **Collaborate (Agente Atendente e Analista Manual)**: Sinergia na formulação de uma resposta inicial coerente.
*   **Observe & Reason (Agente Atendente)**: Aplica limites e o formato de saída à resposta, garantindo conformidade e usabilidade.
*   **Act (Agente Atendente)**: Gerencia cenários de fallback, solicitando esclarecimentos ou informando sobre limitações do sistema.
*   **Act (Agente Atendente)**: Entrega a resposta final estruturada ao aluno.

**Estado Atual do Sistema RAG:**
Os 27 documentos DOCX foram processados com sucesso e chunkados, resultando em 90 `texts` prontos para serem indexados em um banco de dados vetorial. Embora o serviço de recuperação via banco de dados vetorial esteja atualmente no estágio conceitual (referido como "serviços que ainda não foram feitos" em cenários de fallback), o workflow ReAct e a configuração do 'cérebro' do agente foram definidos para integrar-se perfeitamente com a futura implementação desses serviços. O sistema está pronto para a próxima fase, que envolverá a construção e integração do módulo de recuperação real e a implementação dos LLMs para cada agente.

Este arcabouço lógico assegura que o agente esteja preparado para operar de maneira eficiente, precisa e confiável, utilizando a base de conhecimento para responder às consultas dos alunos de forma controlada e útil.

# Task
Configure the agent's 'brain' by defining its Objective, Boundaries, Output Format, and Fallback mechanism to ensure it can effectively assist with extension activity submissions. This configuration will be a crucial step in setting up the Retrieval-Augmented Generation (RAG) system.

## Create Agent Memory File

### Subtask:
Programmatically create an empty text file named `regras_memoria.txt` in the Colab environment. This file will serve as the agent's long-term memory for corrections and learned rules. If the file already exists, ensure it is ready for appending new rules.

**Reasoning**:
To create the `regras_memoria.txt` file as specified in the instructions, I will use the `touch` command in a code block.
"""

import os

file_name = 'regras_memoria.txt'
file_path = os.path.join('/content/', file_name)

# Create the file if it doesn't exist, or update its timestamp if it does
# This makes it ready for appending, as per the subtask instruction.
!touch "{file_path}"

print(f"File '{file_path}' created or updated.")

# Verify its creation
if os.path.exists(file_path):
    print(f"Confirmation: '{file_name}' exists at '{file_path}'.")
else:
    print(f"Error: '{file_name}' does not exist at '{file_path}'.")

"""## Understand Student Request (Attendant Agent)

### Subtask:
The 'Attendant' agent will initiate interaction with the student to understand their specific query regarding extension activity submissions. This includes gathering essential information such as the student's course and the deadline, which are crucial for context and for triggering fallback mechanisms if missing. This is the initial 'Observe' step in ReAct.

"""

import os

file_path = '/content/regras_memoria.txt'
regras_memoria_content = ""

if os.path.exists(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        regras_memoria_content = f.read().strip()

if regras_memoria_content:
    print(f"Conteúdo de 'regras_memoria.txt' lido:\n---\n{regras_memoria_content}\n---")
    print("Regras aprendidas disponíveis na memória.")
else:
    print("O arquivo 'regras_memoria.txt' está vazio ou não contém regras aprendidas.")

# This variable will be used in the next conceptual step
memory_rules = regras_memoria_content

"""## Outline ReAct Workflow Sequence

### Subtask:
Detail the collaborative sequence of actions for the two agents within the ReAct framework: Attendant's observation, Manual Analyst's retrieval and memory consultation, Manual Analyst's rule extraction, collaborative response formulation, Attendant's application of boundaries and output format, Attendant's handling of fallback scenarios (including logging corrections to memory), and finally, the Attendant's delivery of the structured response.

## Acknowledge Current RAG System Status

### Subtask:
Explicitly confirm the current state of the RAG system, noting the successful processing and chunking of DOCX documents, the creation and readiness of 'regras_memoria.txt', and the conceptual status of the core RAG retrieval services.
"""